CREATE ROLE rails WITH LOGIN;
CREATE DATABASE earthquake_api_test;
CREATE DATABASE ruby_test;
CREATE USER rails WITH PASSWORD '123456789';
GRANT ALL PRIVILEGES ON SCHEMA public TO rails;
GRANT ALL PRIVILEGES ON DATABASE my_app_production TO rails;
GRANT ALL PRIVILEGES ON DATABASE ruby_test TO rails;
